logging:
  level:
    org:
      atmosphere: warn
server:
  port: ${PORT:8090}
spring:
  output:
    ansi:
      enabled: always
  mustache:
    check-template-location: false
  # This is a workaround for https://github.com/vaadin/spring/issues/381
  servlet:
    multipart:
      enabled: false
vaadin.pnpm.enable: true
# To improve the performance during development.
# For more information https://vaadin.com/docs/flow/spring/tutorial-spring-configuration.html#special-configuration-parameters
# vaadin.whitelisted-packages= org/vaadin/example

###----------------------------------------------------------------------------------------------###
#  Feign Client Config
###----------------------------------------------------------------------------------------------###
feign:
  user:
    name: user-ws
    url: http://localhost:8091/
###----------------------------------------------------------------------------------------------###