logging:
  level:
    org:
      atmosphere: warn
server:
  port: ${PORT:8090}
spring:
  output:
    ansi:
      enabled: always
  mustache:
    check-template-location: false
  # This is a workaround for https://github.com/vaadin/spring/issues/381
  servlet:
    multipart:
      enabled: false
vaadin.pnpm.enable: true
# To improve the performance during development.
# For more information https://vaadin.com/docs/flow/spring/tutorial-spring-configuration.html#special-configuration-parameters
vaadin.whitelisted-packages: in/home/user/ui, org/vaadin/gatanaso

###----------------------------------------------------------------------------------------------###
#  Feign Client Config
###----------------------------------------------------------------------------------------------###
feign:
  user-url: http://localhost:8091/
###----------------------------------------------------------------------------------------------###
#  Feign Client Logging Config
###----------------------------------------------------------------------------------------------###
logging.level:
  root: WARN
  in.home: TRACE
  in.home.user.ui.feign.client: WARN
###----------------------------------------------------------------------------------------------###